---
- name: Upgrade Silverblue to latest ostree image
  command: rpm-ostree upgrade
  
# reboot the machine after upgrade
# Layering after upgrade without reboot could cause ostree image corruption
- name: Reboot the machine
  reboot:
  
# python3-psutil package is needed by dconf module
- name: Install psutil
  command: rpm-ostree install --idempotent python3-psutil

- name: Reboot the machine
  reboot:

- name: Create htpc user
  user:
    name: "{{ username }}"

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install kodi and VLC
  community.general.flatpak:
    name:
      - tv.kodi.Kodi
      - org.videolan.VLC
    state: present

- name: Create gnome-initial-setup-done file
  become_user: "{{ username }}"
  become: yes
  copy:
    dest: "/home/{{ username }}/.config/gnome-initial-setup-done"
    content: |
      yes

- name: Add autologin to htpc user
  blockinfile:
    path: "/etc/gdm/custom.conf"
    insertafter: "\\[daemon\\]"
    block: |
      AutomaticLoginEnable=True
      AutomaticLogin={{ username }}

- name: Disable specific gnome features
  become_user: "{{ username }}"
  become: yes
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
      # Display dim
    - key: "/org/gnome/settings-daemon/plugins/power/idle-dim"
      value: "false"
      # Sleep over time
    - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
      value: "'nothing'"
      # Screensaver
    - key: "/org/gnome/desktop/screensaver/lock-enabled"
      value: "false"
      # Automatic updates
    - key: "/org/gnome/software/download-updates"
      value: "false"

# If you don't want automatic updates run the ansible with `--skip-tags auto-updates`
- name: Install upgrade service
  copy:
    src: upgrade.service
    dest: /etc/systemd/system/
  tags:
    - auto-updates

- name: Install upgrade timer
  copy:
    src: upgrade.timer
    dest: /etc/systemd/system/
  tags:
    - auto-updates

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable upgrade timer
  ansible.builtin.systemd:
    name: upgrade.timer
    state: started
    enabled: yes
  tags:
    - auto-updates
    
- name: Reboot machine
  reboot:
