---
- name: Upgrade Silverblue to latest ostree image
  command: rpm-ostree upgrade
  
# reboot the machine after upgrade
# Layering after upgrade without reboot could cause ostree image corruption
- name: Reboot the machine
  reboot:
  
# python3-psutil package is needed by dconf module
- name: Install psutil
  command: rpm-ostree install --idempotent python3-psutil

- name: Reboot the machine
  reboot:

- name: Create htpc user
  user:
    name: "{{ username }}"

- name: Add the flathub flatpak repository remote
  become_user: "{{ username }}"
  become: yes
  community.general.flatpak_remote:
    method: user
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

# The Brave browser is only on flathub-beta right now
- name: Add the flathub flatpak repository remote
  become_user: "{{ username }}"
  become: yes
  community.general.flatpak_remote:
    method: user
    name: flathub-beta
    state: present
    flatpakrepo_url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo

- name: Install Kodi and VLC flatpaks
  become_user: "{{ username }}"
  become: yes
  community.general.flatpak:
    name:
      - tv.kodi.Kodi
      - org.videolan.VLC
    method: user
    state: present

- name: Install Brave flatpak
  become_user: "{{ username }}"
  become: yes
  community.general.flatpak:
    name:
      - com.brave.Browser
    method: user
    state: present
    remote: flathub-beta

- name: Create a directory if it does not exist
  become_user: "{{ username }}"
  become: yes
  ansible.builtin.file:
    path: "/home/{{ username }}/.config"
    state: directory
    mode: '0755'

- name: Create gnome-initial-setup-done file
  become_user: "{{ username }}"
  become: yes
  copy:
    dest: "/home/{{ username }}/.config/gnome-initial-setup-done"
    content: |
      yes

- name: Add autologin to htpc user
  blockinfile:
    path: "/etc/gdm/custom.conf"
    insertafter: "\\[daemon\\]"
    block: |
      AutomaticLoginEnable=True
      AutomaticLogin={{ username }}

- name: Disable specific gnome features
  become_user: "{{ username }}"
  become: yes
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
      # Display dim
    - key: "/org/gnome/settings-daemon/plugins/power/idle-dim"
      value: "false"
      # Sleep over time
    - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
      value: "'nothing'"
      # Screensaver
    - key: "/org/gnome/desktop/screensaver/lock-enabled"
      value: "false"
      # Automatic updates
    - key: "/org/gnome/software/download-updates"
      value: "false"

# If you don't want automatic updates run the ansible with `--skip-tags auto-updates`
- name: Install upgrade service
  copy:
    src: upgrade.service
    dest: /etc/systemd/system/
  tags:
    - auto-updates

- name: Install upgrade timer
  copy:
    src: upgrade.timer
    dest: /etc/systemd/system/
  tags:
    - auto-updates

- name: Create user systemd directory
  become_user: "{{ username }}"
  become: yes
  file:
    path: ~/.config/systemd/user/
    state: directory

# Flatpak needs to be run by currently logged user
- name: Install flatpak update service
  copy:
    src: flatpak-update.service
    dest: ~/.config/systemd/user/flatpak-update.service
  become_user: "{{ username }}"
  become: yes
  tags:
    - auto-updates

- name: Install flatpak-update timer
  copy:
    src: flatpak-update.timer
    dest: ~/.config/systemd/user/flatpak-update.timer
  become_user: "{{ username }}"
  become: yes
  tags:
    - auto-updates

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable upgrade timer
  ansible.builtin.systemd:
    name: upgrade.timer
    state: started
    enabled: yes
  tags:
    - auto-updates

- name: Find uid of user
  command: "id -u {{ username }}"
  register: the_user_uid
  check_mode: no # Run even in check mode, otherwise the playbook fails with --check.
  changed_when: false

- name: Determine XDG_RUNTIME_DIR
  set_fact:
    xdg_runtime_dir: "/run/user/{{ the_user_uid.stdout }}"
  changed_when: false

- name: Enable flatpak-update timer
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  ansible.builtin.systemd:
    name: flatpak-update.timer
    state: started
    enabled: yes
    scope: user
  become_user: "{{ username }}"
  become: yes
  tags:
    - auto-updates

- name: Reboot machine
  reboot:
