---
- name: Install and configure HTPC
  hosts: all
  remote_user: root
  roles:
    - role: htpc

  tasks:
  - name: Upgrade Silverblue to latest ostree image
    command: rpm-ostree upgrade
    
  # reboot the machine after upgrade
  # Layering after upgrade without reboot could cause ostree image corruption
  - name: Reboot the machine
    reboot:
    
  ## Cron is missing on Silverblue and we need it to setup automatic updates later
  #- name: Install cron
  #  command: rpm-ostree install --idempotent cronie

  ## python3-psutil package is needed by dconf module
  #- name: Install psutil
  #  command: rpm-ostree install --idempotent python3-psutil

  #- name: Reboot the machine
  #  reboot:

  - name: Create kodi user
    user:
      name: kodi

  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  #  This is not working right now - https://github.com/ansible/ansible/pull/48049
  - name: Install kodi
    become_user: kodi
    flatpak:
      name: tv.kodi.Kodi
      state: present
      method: user

  ## So we need another method
  #- name: Install kodi
  #  command: flatpak install -y flathub tv.kodi.Kodi

  #- name: Create autostart directory
  #  become_user: kodi
  #  become: true
  #  file:
  #    path: "/home/kodi/.config/autostart"
  #    state: directory

  - name: Create gnome-initial-setup-done file
    become_user: kodi
    become: true
    copy:
      dest: "/home/kodi/.config/gnome-initial-setup-done"
      content: |
        yes

  #- name: Configure kodi as autostart application
  #  become_user: kodi
  #  become: true
  #  file:
  #    src: "/var/lib/flatpak/exports/share/applications/tv.kodi.Kodi.desktop"
  #    path: "/home/kodi/.config/autostart/tv.kodi.Kodi.desktop"
  #    state: link

  - name: Add autologin to kodi user
    blockinfile:
      path: "/etc/gdm/custom.conf"
      insertafter: "\\[daemon\\]"
      block: |
        AutomaticLoginEnable=True
        AutomaticLogin=kodi

  - name: Disable specific gnome features
    become_user: kodi
    become: true
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
    loop:
        # Display dim
      - key: "/org/gnome/settings-daemon/plugins/power/idle-dim"
        value: "false"
        # Sleep over time
      - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        # Screensaver
      - key: "/org/gnome/desktop/screensaver/lock-enabled"
        value: "false"
        # Automatic updates
      - key: "/org/gnome/software/download-updates"
        value: "false"

  # If you don't want automatic updates run the ansible with `--skip-tags auto-updates`
  - name: Setup automatic updates
    cron:
      name: "Updates"
      weekday: 3
      minute: 0
      hour: 4
      job: "flatpak update -y; rpm-ostree upgrade; reboot"
    tags:
      - auto-updates

  - name: Reboot machine
    reboot:
